services:
  - type: web
    name: securevault-backend
    runtime: java
    region: oregon
    plan: free
    branch: main
    rootDir: securevault-backend
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/securevault-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:./data/securevault_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
      - key: SPRING_DATASOURCE_DRIVER
        value: org.h2.Driver
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://secure-vault-green-five.vercel.app
